scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # `basic` tests configured to test 2 CRs
    - basic:
        cr-manifest:
          - "deploy/crds/charts.helm.k8s.io_v1alpha1_yugaware_cr.yaml"
        namespace: "yugaware-operator"
    # `olm` tests configured to test 2 CRs
    - olm:
        cr-manifest:
          - "deploy/crds/charts.helm.k8s.io_v1alpha1_yugaware_cr.yaml"
        namespace: "yugaware-operator"
        csv-path: "deploy/olm-catalog/yugabyte-platform-operator/1.0.0/yugabyte-platform-operator.v1.0.0.clusterserviceversion.yaml"