# permissions for end users to edit ybplatforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ybplatform-editor-role
rules:
- apiGroups:
  - yugabyte.com
  resources:
  - ybplatforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yugabyte.com
  resources:
  - ybplatforms/status
  verbs:
  - get
