# permissions for end users to view ybplatforms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ybplatform-viewer-role
rules:
- apiGroups:
  - yugabyte.com
  resources:
  - ybplatforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - yugabyte.com
  resources:
  - ybplatforms/status
  verbs:
  - get
