apiVersion: apps/v1
kind: Deployment
metadata:
  name: yugabyte-platform-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: yugabyte-platform-operator
  template:
    metadata:
      labels:
        name: yugabyte-platform-operator
    spec:
      serviceAccountName: yugabyte-platform-operator
      containers:
        - name: yugabyte-platform-operator
          # Replace this with the built image name
          image: nchandrappa/yugabyte-platform-operator:v1.0.0-b4
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "yugabyte-platform-operator"
